name: Build & Push

on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: backend/
          file: docker/Dockerfile.backend
          push: true
          tags: ghcr.io/ku113p/interview-backend:latest

  mcp:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: backend/
          file: docker/Dockerfile.mcp
          push: true
          tags: ghcr.io/ku113p/interview-mcp:latest

  promo:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: docker/Dockerfile.frontend
          push: true
          tags: ghcr.io/ku113p/interview-promo:latest
